                <div class="rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
                    <h3 class="text-xl font-bold text-zinc-900 dark:text-white">Data Mahasiswa UPNVJ</h3>
                    <div class="mt-6 grid grid-cols-1 gap-6 md:grid-cols-2">
                        <div><label for="nim" class="block text-sm font-medium">NIM</label><input id="nim" type="text" wire:model="nim" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('nim') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="no_wa" class="block text-sm font-medium">No. WhatsApp</label><input id="no_wa" type="text" wire:model="no_wa" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('no_wa') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="fakultas" class="block text-sm font-medium">Fakultas</label><input id="fakultas" type="text" wire:model="fakultas" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('fakultas') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="program_studi" class="block text-sm font-medium">Program Studi</label><input id="program_studi" type="text" wire:model="program_studi" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('program_studi') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="kualifikasi_pendidikan" class="block text-sm font-medium">Kualifikasi Pendidikan</label><input id="kualifikasi_pendidikan" type="text" wire:model="kualifikasi_pendidikan" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('kualifikasi_pendidikan') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="total_sks" class="block text-sm font-medium">Total SKS</label><input id="total_sks" type="number" wire:model="total_sks" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('total_sks') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="status_semester" class="block text-sm font-medium">Status Semester</label><input id="status_semester" type="text" wire:model="status_semester" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('status_semester') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="no_ktp" class="block text-sm font-medium">No KTP</label><input id="no_ktp" type="text" wire:model="no_ktp" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('no_ktp') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="tempat_lahir" class="block text-sm font-medium">Tempat Lahir</label><input id="tempat_lahir" type="text" wire:model="tempat_lahir" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('tempat_lahir') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="tanggal_lahir" class="block text-sm font-medium">Tanggal Lahir</label><input id="tanggal_lahir" type="date" wire:model="tanggal_lahir" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('tanggal_lahir') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="jenis_kelamin" class="block text-sm font-medium">Jenis Kelamin</label><select id="jenis_kelamin" wire:model="jenis_kelamin" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white"><option value="">Pilih Jenis Kelamin</option><option value="L">Laki-laki</option><option value="P">Perempuan</option></select>@error('jenis_kelamin') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="kode_pos_rumah" class="block text-sm font-medium">Kode Pos*</label><input id="kode_pos_rumah" type="text" wire:model="kode_pos_rumah" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('kode_pos_rumah') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="nama_perusahaan" class="block text-sm font-medium">Nama Institusi / Perusahaan*</label><input id="nama_perusahaan" type="text" wire:model="nama_perusahaan" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('nama_perusahaan') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div><label for="kode_pos_perusahaan" class="block text-sm font-medium">Kode POS Perusahaan*</label><input id="kode_pos_perusahaan" type="text" wire:model="kode_pos_perusahaan" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white">@error('kode_pos_perusahaan') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                        <div class="md:col-span-2"><label for="alamat_rumah" class="block text-sm font-medium">Alamat Rumah</label><textarea id="alamat_rumah" wire:model="alamat_rumah" rows="3" class="mt-2 block w-full rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700 dark:bg-zinc-800 dark:text-white"></textarea>@error('alamat_rumah') <p class="mt-2 text-sm text-red-600">{{ $message }}</p> @enderror</div>
                    </div>
                </div>
